name: xdev_cli
description: A sample command-line application.
version: 1.1.0

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  xdev: xdev