name: xdev_cli
description: A powerful Flutter project generator CLI that helps developers quickly scaffold Flutter apps with clean architecture and folder structure.
repository: https://github.com/xdevsoft0/xdev_cli
homepage: https://pub.dev/packages/xdev_cli
version: 1.0.3

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  xdev: xdev